name: High vulns Snyk PR scan

on: pull_request

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          cd lambda
          npm ci
          npm test
        env:
          CI: true
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --org=dwp-dataworks --file=lambda/package-lock.json
