name: High vulns Snyk PR scan

on: pull_request

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 12.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --org=dwp-dataworks
